-- types of tokens
return require("parse.utils").enum({
    "Oper",
    "Number",
    "String",
    "Name",
    "Backslash",
    "Comma",
    "Dot",
    "Semi",
    "LBrace",
    "RBrace",
    "LPar",
    "RPar",
    "LSQB",
    "RSQB",
    "Return",
    "Export",
    "Let",
    "Type",
    "Of",
    "Nil",
    "True",
    "False",
    "If", "Else", "Do", "While", "Loop", "Break",
    "Error",
    "EOF"
}, true)
